#!/usr/bin/python3

import argparse
import signal
import sys
from validproxy import validproxy

def banner():
    white = "\033[97m"
    green = "\033[92m"
    reset = "\033[0m"

    print(f"""
{white}+--------------------------------------------------------------------+
{white}| {green}██████╗ ██████╗  ██████╗ ██╗  ██╗██╗   ██╗ █████╗  ██████╗███████╗ {white}|
{white}|{green} ██╔══██╗██╔══██╗██╔═══██╗╚██╗██╔╝╚██╗ ██╔╝██╔══██╗██╔════╝██╔════╝ {white}|
{white}|{green} ██████╔╝██████╔╝██║   ██║ ╚███╔╝  ╚████╔╝ ███████║██║     █████╗   {white}|
{white}|{green} ██╔═══╝ ██╔══██╗██║   ██║ ██╔██╗   ╚██╔╝  ██╔══██║██║     ██╔══╝   {white}|
{white}|{green} ██║     ██║  ██║╚██████╔╝██╔╝ ██╗   ██║   ██║  ██║╚██████╗███████╗ {white}|
{white}|{green} ╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝╚══════╝ {white}|
{white}+--------------------------------------------------------------------+{reset}""")

def read_proxies_from_file(file_path):
    with open(file_path, 'r') as file:
        proxies = [line.strip() for line in file if line.strip()]
    return proxies

def save_valid_proxies(file_path, valid_proxies):
    with open(file_path, 'w') as file:
        for proxy in valid_proxies:
            file.write(f"{proxy}\n")

def signal_handler(sig, frame):
    print('\n\033[91mProcess interrupted. Exiting gracefully...\033[0m')
    sys.exit(0)

def main():
    banner()

    parser = argparse.ArgumentParser(description="Proxy Validator")
    parser.add_argument('--proxy-list', type=str, help='Path to the proxy list file')
    parser.add_argument('--valid-proxy', type=str, help='Path to save valid proxies')
    parser.add_argument('--main', action='store_true', help='Run in interactive mode to ask for inputs')

    args = parser.parse_args()

    if args.main:
        proxy_list = input(f"\033[97m[\033[92m+\033[97m] \033[92mEnter the proxy file path : \033[0m")
        valid_proxy_save = input(f"\033[97m[\033[92m+\033[97m] \033[92mEnter the valid proxy output file path : \033[0m")
    else:
        if not args.proxy_list:
            parser.error('--proxy-list is required unless --main is used')
        proxy_list = args.proxy_list
        valid_proxy_save = args.valid_proxy if args.valid_proxy else "valid_proxy.txt"

    proxies = read_proxies_from_file(proxy_list)
    valid_proxies = []

    for proxy in proxies:
        if validproxy(proxy):
            print(f'\033[97m[\033[92m+\033[97m] \033[92mValid proxy : {proxy}\033[0m')
            valid_proxies.append(proxy)
        else:
            print(f'\033[97m[\033[91m-\033[97m] \033[91mInvalid proxy : {proxy}\033[0m')

    save_valid_proxies(valid_proxy_save, valid_proxies)

if __name__ == "__main__":
    signal.signal(signal.SIGINT, signal_handler)
    main()
